"""Robustness check: every Arena number again on one row per distinct text. No API call.

The generators repeat texts (#54): the emails under attack hold 189 distinct texts in 200
rows, the clean emails 161, the router 61 in 120. The published intervals already resample
distinct texts, but a repeated text still counts twice in the point estimate. This report
keeps the first row of each distinct text (file order), drops the rest, and recomputes the
Arena statistics from the same committed checkpoints, so a reader can see which numbers
lean on the repeats. It writes docs/robustness-distinct-2026-09.md and .json.

  python scripts/distinct_report.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from arena_report import (  # noqa: E402
    ARENA,
    DATASETS,
    JEV,
    fmt,
    ground_truth_tier,
    records,
    summarize,
)

from judge_audit.report import interval_of  # noqa: E402
from judge_audit.runner import load_jsonl  # noqa: E402

OUT = ROOT / "docs" / "robustness-distinct-2026-09"
KEYS = ("n", "accuracy", "accuracy_ci", "accuracy_ci_method", "zero_error_coverage",
        "zero_error_coverage_ci", "zero_error_coverage_ci_method", "mean_conf_correct",
        "mean_conf_wrong", "ece")
TITLES = {"email-clean": "Clean emails", "email-adversarial": "Emails under attack",
          "router-bare": "Router, bare labels", "router-described": "Router, described options"}


def first_of_each_text(rows: list[dict]) -> set[int]:
    """Row indices that are the first occurrence of their state text, in file order."""
    first: dict[str, int] = {}
    for i, r in enumerate(rows):
        first.setdefault(r["state"], i)
    return set(first.values())


def segments(rows: list[dict], idx) -> dict[str, int]:
    """Router rows per segment: easy, hard, or easy with an injected instruction."""
    out: dict[str, int] = {}
    for i in idx:
        m = rows[i].get("_meta") or {}
        k = "injected" if m.get("adversarial") else str(m.get("difficulty"))
        out[k] = out.get(k, 0) + 1
    return dict(sorted(out.items()))


def both(recs: list[dict], ds: str, rows: list[dict]) -> dict:
    keep = first_of_each_text(rows)
    pick = lambda s: {k: s.get(k) for k in KEYS}  # noqa: E731
    return {"all": pick(summarize(recs, ds, rows)),
            "distinct": pick(summarize([r for r in recs if r["idx"] in keep], ds, rows))}


def collect() -> dict:
    """The Arena's judges, with the Arena's rules: full-dataset runs only, complete only."""
    out: dict[str, dict] = {}
    for ds, (labels, q) in DATASETS.items():
        rows = load_jsonl(str(ROOT / labels))
        keep = first_of_each_text(rows)
        out[ds] = {"rows": len(rows), "distinct_texts": len(keep), "judges": {}}
        if ds.startswith("router"):
            out[ds]["segments"] = {"all": segments(rows, range(len(rows))),
                                   "distinct": segments(rows, sorted(keep))}
        recs, _ = records(labels, ROOT / JEV[ds], q)
        out[ds]["judges"]["jev"] = both(recs, ds, rows)
        for d in sorted(p for p in ARENA.iterdir() if p.is_dir()):
            ck = d / f"{ds}.ckpt.jsonl"
            if not ck.exists():
                continue
            recs, run = records(labels, ck, q)
            if run.get("rows_subset") or len(recs) < len(rows):
                continue
            out[ds]["judges"][d.name] = both(recs, ds, rows)
    out["headline"] = headline(out["email-adversarial"]["judges"])
    return out


def headline(judges: dict) -> dict:
    """The README headline on distinct texts: Gemini's exact upper bound below Jev's lower."""
    g, j = judges["gemini-3-flash"]["distinct"], judges["jev"]["distinct"]
    return {"gemini_zero_error_coverage": g["zero_error_coverage"],
            "gemini_upper": g["zero_error_coverage_ci"][1],
            "gemini_method": g["zero_error_coverage_ci_method"],
            "jev_zero_error_coverage": j["zero_error_coverage"],
            "jev_ci": j["zero_error_coverage_ci"],
            "separated": g["zero_error_coverage_ci"][1] < j["zero_error_coverage_ci"][0]}


def mix(seg: dict[str, int]) -> str:
    return " / ".join(f"{n} {k}" for k, n in seg.items())


def cell(s: dict, key: str) -> str:
    return f"{fmt(s[key], True)}{interval_of(s, key + '_ci', pct=True)}"


def render(data: dict) -> str:
    h = data["headline"]
    verdict = ("holds" if h["separated"] else "does **not** hold")
    lines = [
        "# Robustness check: one row per distinct text",
        "",
        "> Generated by `scripts/distinct_report.py` from the committed checkpoints — no API "
        "call. Regenerated in CI.",
        "",
        "The generators repeat some texts (#54). The published intervals already resample "
        "distinct texts, but a repeated text still counts twice in the point estimate. Here "
        "every Arena statistic is recomputed on the **first row of each distinct text** (file "
        "order), so a reader can see which numbers lean on the repeats. Same judges, same "
        "rules as the Arena table (full-dataset runs only); same 95 % intervals over distinct "
        "texts (the exact Clopper–Pearson binomial interval where the bootstrap cannot move, "
        "marked †).",
        "",
        f"**The README headline {verdict} on distinct texts.** Under attack, on "
        f"{data['email-adversarial']['distinct_texts']} distinct texts, Gemini 3 Flash's "
        f"zero-error coverage is {fmt(h['gemini_zero_error_coverage'], True)} "
        f"(95 % upper bound {h['gemini_upper'] * 100:.1f} %) and Jev's is "
        f"{fmt(h['jev_zero_error_coverage'], True)} [{h['jev_ci'][0] * 100:.1f}, "
        f"{h['jev_ci'][1] * 100:.1f}]; the intervals "
        f"{'do not overlap' if h['separated'] else 'overlap'}.",
        "",
        f"**Read the router with care.** Deduplicating the router keeps "
        f"{data['router-bare']['distinct_texts']} of {data['router-bare']['rows']} rows, and "
        f"the repeats sit in its easy and hard segments: it goes from "
        f"{mix(data['router-bare']['segments']['all'])} to "
        f"{mix(data['router-bare']['segments']['distinct'])}. So the distinct-text router "
        "is mostly the injected segment, and its accuracy moves because the *question mix* "
        "changes, not only because repeats are gone. Compare the router rows with that in "
        "mind; the email datasets keep their mix.",
        "",
    ]
    for ds, title in TITLES.items():
        d = data[ds]
        gt = ground_truth_tier(DATASETS[ds][0])
        lines += [f"## {title} — {d['rows']} rows, {d['distinct_texts']} distinct texts "
                  f"({gt.tier} {gt.label})", "",
                  "| judge | accuracy: all rows | accuracy: distinct texts | zero-error "
                  "coverage: all rows | zero-error coverage: distinct texts | conf right / "
                  "wrong: distinct texts |",
                  "|---|---|---|---|---|---|"]
        for slug, s in d["judges"].items():
            a, b = s["all"], s["distinct"]
            lines.append(f"| {slug} | {cell(a, 'accuracy')} | {cell(b, 'accuracy')} | "
                         f"{cell(a, 'zero_error_coverage')} | {cell(b, 'zero_error_coverage')}"
                         f" | {fmt(b['mean_conf_correct'])} / {fmt(b['mean_conf_wrong'])} |")
        lines.append("")
    lines += ["## Caveats", "",
              "- Every dataset is GT-1 synthetic: ground truth by construction, small n.",
              "- Which row of a repeated text is kept is a rule (the first in file order), "
              "not a sample; a judge that answered the repeats differently is scored on one "
              "of its answers only.",
              "- This does not replace a dataset without repeats; the pre-registered "
              "replication on v2 data is the stronger test.", ""]
    return "\n".join(lines)


def main() -> None:
    data = collect()
    OUT.with_suffix(".json").write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    OUT.with_suffix(".md").write_text(render(data), encoding="utf-8")
    h = data["headline"]
    print(f"headline on distinct texts: {'separated' if h['separated'] else 'NOT separated'}"
          f" -> {OUT.with_suffix('.md').relative_to(ROOT)}")


if __name__ == "__main__":
    main()
